name: module_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  image_picker: ^1.0.4
  flutter:
    sdk: flutter
  #http
  http: ^1.1.0
  #webview
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ebGaramond
      fonts:
        - asset: assets/fonts/eb_garamond.ttf
  uses-material-design: true
